SELECT * FROM customers_shopping.customers_shopping_behavior;
-- Q1 What is the total revenue generated by male vs female customers?
SELECT 
    gender, SUM(purchase_amount) AS revenue_generated
FROM
    customers_shopping_behavior
GROUP BY gender;

-- Q2 Which customer used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, purchase_amount
FROM
    customers_shopping_behavior
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customers_shopping_behavior);

-- Q3 Which are the top 5 products with the highest average review rating?
SELECT 
    category,
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM
    customers_shopping_behavior
GROUP BY category , item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- Q4  Compare the average purchase amounts between standard and express shipping.
SELECT 
    shipping_type, ROUND(AVG(purchase_amount), 2)
FROM
    customers_shopping_behavior
WHERE
    shipping_type IN ('Express' , 'Standard')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_subsribed,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM
    customers_shopping_behavior
GROUP BY subscription_status
ORDER BY avg_spend , total_revenue DESC;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied?
 SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'Yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customers_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7 Segment customers into New, Returning , and Loyal based on their total numbers of previous purchases, 
-- and show the count of each segment .

with customer_type as (
select customer_id , previous_purchases ,
case when previous_purchases =1 then 'New' 
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment from customers_shopping_behavior
)
select customer_segment , count(*) as number_of_customer from customer_type
group by customer_segment;

-- Q8 What are the top 3 most purchased products within each category?

with cte as(
select item_purchased , category , sum(purchase_amount)as total_sales , 
dense_rank() over(partition by category order by sum(purchase_amount) desc)  as rn
from customers_shopping_behavior
group by item_purchased , category)

select item_purchased , category ,rn , total_sales from cte
where rn<=3;
 
-- Outwear category offers only two products.
select * from customers_shopping_behavior
where category = "Outerwear" and item_purchased not in ('jacket' , 'coat');

-- Q9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT 
    COUNT(customer_id) AS repeat_buyers, subscription_status
FROM
    customers_shopping_behavior
WHERE
    previous_purchases > 5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution of each age group?

SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customers_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;






